package com.example.bookstore.enums;

public enum AuthorRole {

    AUTHOR, ILLUSTRATOR, COLORIST, TRANSLATOR,
    INTRODUCTION_AUTHOR, FOREWORD_AUTHOR, AFTERWORD_AUTHOR,
    PREFACE_AUTHOR, ANNOTATIONS, LETTERER, CONTRIBUTOR,
    EDITOR, NARRATOR, ARTIST, NOTES, COMMENTARY, OTHER

}
